In [7]:
import pandas as pd
df = pd.read_csv('20210910-sensor-1-accelerometer.csv', sep=';', skiprows=1, index_col=False)
df

,sensor-id,time,excel_time,x,y,z,abs,RoT_or_steps
0,1,12:02:16.234,44449.501577,-4.168,3.734,8.575,10.240,0.0
1,1,12:02:16.447,44449.501579,-2.337,2.270,9.649,10.184,0.0
2,1,12:02:16.584,44449.501581,-2.275,2.459,9.619,10.185,0.0
3,1,12:02:16.725,44449.501582,-2.042,2.273,9.653,10.126,0.0
4,1,12:02:16.843,44449.501584,-2.168,2.227,10.016,10.487,0.0
...,...,...,...,...,...,...,...,...
11689,1,12:53:51.950,44449.537407,-1.706,4.234,8.409,9.568,75.0
11690,1,12:53:52.089,44449.537408,-2.960,3.721,10.953,11.940,76.0
11691,1,12:53:52.213,44449.537410,-0.261,2.871,10.450,10.841,76.0
11692,1,12:53:52.329,44449.537411,-2.083,3.400,8.126,9.051,76.0
11693,1,12:53:52.469,44449.537413,-2.648,3.363,9.415,10.343,76.0